services:
  db:
    image: lcaohoanq/snake_game_app:2.0
    container_name: spring_snake_game
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
